# Generated by Django 5.2.3 on 2025-06-23 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_newsletter_subscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField(help_text='Brief description of the post', max_length=500)),
                ('content', models.TextField(help_text='Main content of the blog post')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 60 chars)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=10)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this post on homepage')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='portfolio_app.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='portfolio_app.blogtag')),
            ],
            options={
                'ordering': ['-publish_date'],
                'indexes': [models.Index(fields=['-publish_date'], name='portfolio_a_publish_30f29b_idx'), models.Index(fields=['status'], name='portfolio_a_status_64fc4f_idx'), models.Index(fields=['is_featured'], name='portfolio_a_is_feat_71ffbc_idx')],
            },
        ),
    ]
