# Generated by Django 5.2.3 on 2025-06-23 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_blogcategory_blogtag_blogpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Workshop title', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed workshop description')),
                ('short_description', models.TextField(help_text='Brief description for cards/listings', max_length=300)),
                ('featured_image', models.ImageField(help_text='Workshop cover image', upload_to='workshops/images/')),
                ('is_paid', models.BooleanField(default=False, help_text='Is this a paid workshop?')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price (required for paid workshops)', max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', help_text='Currency code (e.g., INR, USD)', max_length=3)),
                ('start_date', models.DateTimeField(help_text='Workshop start date and time')),
                ('end_date', models.DateTimeField(help_text='Workshop end date and time')),
                ('duration_hours', models.PositiveIntegerField(help_text='Duration in hours')),
                ('max_participants', models.PositiveIntegerField(default=50, help_text='Maximum number of participants')),
                ('registered_count', models.PositiveIntegerField(default=0, help_text='Current number of registrations')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('requirements', models.TextField(blank=True, help_text='Prerequisites or requirements')),
                ('what_you_learn', models.TextField(blank=True, help_text='What participants will learn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description', max_length=160)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['-start_date'], name='portfolio_a_start_d_2201e4_idx'), models.Index(fields=['status'], name='portfolio_a_status_225bf5_idx'), models.Index(fields=['is_featured'], name='portfolio_a_is_feat_ea9ebb_idx'), models.Index(fields=['is_paid'], name='portfolio_a_is_paid_c5e0cd_idx')],
            },
        ),
    ]
