# Generated by Django 5.2.3 on 2025-06-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Applicant's full name", max_length=100)),
                ('email', models.EmailField(help_text="Applicant's email address", max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Trading experience level', max_length=50)),
                ('motivation', models.TextField(blank=True, help_text='Why do you want to join this workshop? (optional)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portfolio_app.workshop')),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['-applied_at'], name='portfolio_a_applied_120a90_idx'), models.Index(fields=['status'], name='portfolio_a_status_7ab4e4_idx'), models.Index(fields=['workshop', 'status'], name='portfolio_a_worksho_bb2190_idx')],
                'unique_together': {('workshop', 'email')},
            },
        ),
    ]
