# Generated by Django 5.2.3 on 2025-06-24 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_payment_workshopapplication_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('product', 'Digital Product'), ('subscription', 'Subscription'), ('service', 'Trading Service')], max_length=15),
        ),
        migrations.CreateModel(
            name='TradingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name (e.g., Basic Signals)', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('service_type', models.CharField(choices=[('signals', 'Trading Signals'), ('mentorship', 'Mentorship'), ('consultation', 'Consultation'), ('course', 'Trading Course')], default='signals', max_length=20)),
                ('description', models.TextField(help_text='Brief description of the service')),
                ('detailed_description', models.TextField(blank=True, help_text='Detailed description for service page')),
                ('price', models.DecimalField(decimal_places=2, help_text='Service price', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('duration', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='monthly', max_length=20)),
                ('features', models.JSONField(default=list, help_text='List of service features')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as popular/featured')),
                ('is_popular', models.BooleanField(default=False, help_text="Show 'Most Popular' badge")),
                ('booking_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Phone Call'), ('email', 'Email'), ('form', 'Contact Form')], default='whatsapp', help_text='How users can book this service', max_length=20)),
                ('contact_info', models.CharField(blank=True, help_text='Contact number/email for booking', max_length=255)),
                ('booking_url', models.URLField(blank=True, help_text='External booking URL if any')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order to display services')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description', max_length=160)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='portfolio_a_is_acti_0437e8_idx'), models.Index(fields=['is_featured'], name='portfolio_a_is_feat_19bc10_idx'), models.Index(fields=['display_order'], name='portfolio_a_display_e5c983_idx')],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='trading_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio_app.tradingservice'),
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=100)),
                ('email', models.EmailField(help_text='Customer email', max_length=254)),
                ('phone', models.CharField(help_text='Customer phone number', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Customer message/requirements')),
                ('preferred_contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Phone Call'), ('email', 'Email')], default='whatsapp', max_length=20)),
                ('preferred_time', models.CharField(blank=True, help_text='Preferred contact time', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='portfolio_app.tradingservice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='portfolio_a_created_2c86d2_idx'), models.Index(fields=['status'], name='portfolio_a_status_afa0ea_idx'), models.Index(fields=['service'], name='portfolio_a_service_62c313_idx')],
            },
        ),
    ]
