# Generated by Django 5.2.3 on 2025-06-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_userprofile_purchasedcourse'),
    ]

    operations = [
        # Remove newsletter_subscribed field from UserProfile
        migrations.RemoveField(
            model_name='userprofile',
            name='newsletter_subscribed',
        ),
        # Drop Newsletter model
        migrations.DeleteModel(
            name='Newsletter',
        ),
        # Drop Subscriber model
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]