# Generated by Django 5.2.3 on 2025-06-26 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_auto_20250624_1738'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's name", max_length=100)),
                ('email', models.EmailField(help_text="Sender's email address", max_length=254)),
                ('subject', models.CharField(help_text='Message subject', max_length=255)),
                ('message', models.TextField(help_text='Message content')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='new', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the message was first read', null=True)),
                ('replied_at', models.DateTimeField(blank=True, help_text='When a reply was sent', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Sender's IP address", null=True)),
                ('user_agent', models.TextField(blank=True, help_text="Sender's browser user agent")),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Admin user assigned to handle this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='portfolio_a_created_a88ce6_idx'), models.Index(fields=['status'], name='portfolio_a_status_cd00e8_idx'), models.Index(fields=['priority'], name='portfolio_a_priorit_9487b6_idx'), models.Index(fields=['email'], name='portfolio_a_email_ab5c3d_idx')],
            },
        ),
    ]
