# Generated by Django 5.2.3 on 2025-06-26 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_remove_newsletter_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('product', 'Digital Product'), ('subscription', 'Subscription'), ('service', 'Trading Service'), ('course', 'Course')], max_length=15),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Course title', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed course description')),
                ('short_description', models.TextField(help_text='Brief description for cards/listings', max_length=300)),
                ('featured_image', models.ImageField(help_text='Course cover image', upload_to='courses/images/')),
                ('preview_video', models.URLField(blank=True, help_text='Preview video URL')),
                ('course_type', models.CharField(choices=[('video', 'Video Course'), ('live', 'Live Course'), ('workshop', 'Workshop'), ('mentorship', 'Mentorship'), ('signals', 'Trading Signals')], default='video', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('duration_hours', models.PositiveIntegerField(help_text='Course duration in hours')),
                ('lessons_count', models.PositiveIntegerField(default=0, help_text='Number of lessons')),
                ('price', models.DecimalField(decimal_places=2, help_text='Course price', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price (for discounts)', max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('what_you_learn', models.TextField(help_text='What students will learn')),
                ('requirements', models.TextField(blank=True, help_text='Prerequisites or requirements')),
                ('course_content', models.JSONField(default=list, help_text='Course modules and lessons')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='Maximum number of students (null = unlimited)', null=True)),
                ('enrolled_count', models.PositiveIntegerField(default=0, help_text='Current number of enrollments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description', max_length=160)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio_app.course'),
        ),
        migrations.AddField(
            model_name='purchasedcourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio_app.course'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='portfolio_a_razorpa_d7e572_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='portfolio_a_created_63c5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='portfolio_a_is_acti_1e2c08_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured'], name='portfolio_a_is_feat_29435c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type'], name='portfolio_a_course__86d9bd_idx'),
        ),
    ]
